import { createRouter } from '@tanstack/react-router';
// @ts-ignore - routeTree will be generated by TanStack Router Vite plugin
import { routeTree } from './routeTree.gen';

/**
 * Instansiasi router untuk aplikasi Admin.
 */
export const router = createRouter({
  routeTree,
  defaultPreload: 'intent',
  // Basepath untuk Admin adalah root '/'
  basepath: '/',
});

// Registrasi router untuk type safety
declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router;
  }
}
