import { createRouter } from '@tanstack/react-router';
import { setupGateKeeper } from '@genpos/utils';
// @ts-ignore - routeTree will be generated by TanStack Router Vite plugin
import { routeTree } from './routeTree.gen';

// GateKeeper: Mencegah akses langsung ke port 3000 (Auth App)
// Paksa user masuk lewat Gateway (Port 3001)
setupGateKeeper({ gatewayPort: '3000' });

/**
 * Instansiasi router untuk aplikasi Auth.
 * Menggunakan basepath '/sso' agar sinkron dengan konfigurasi Vite.
 */
export const router = createRouter({
  routeTree,
  basepath: '/sso',
  defaultPreload: 'intent',
});

// Register router instance untuk type safety
declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router;
  }
}
