import { createRouter } from '@tanstack/react-router';
// @ts-ignore - routeTree will be generated by TanStack Router Vite plugin
import { routeTree } from './routeTree.gen';

/**
 * Instansiasi router untuk aplikasi Auth.
 * Menggunakan basepath '/sso' agar sinkron dengan konfigurasi Vite.
 */
export const router = createRouter({
  routeTree,
  basepath: '/sso',
  defaultPreload: 'intent',
});

// Register router instance untuk type safety
declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router;
  }
}
